services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /opt/pgsql/data
    ports:
      - 5432:5432
    volumes:
      - $STORAGE_PATH:/opt/pgsql/data
volumes:
  db:
    driver: local